baseURL = "https://kerala.openstreetmap.in/"
languageCode = "en-us"
title = "OpenStreetMap Kerala"
paginate = 10
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = ""
theme = "compose"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2

[permalinks]
  activities = "/:filename/"

[params]
  copyright = "Except where otherwise noted, content on this site is licensed under the [CC-BY-SA license.](https://creativecommons.org/licenses/by-sa/4.0/) {year}"
  subtitle = "Activity log of Open street maps kerala chapter"
  logo = "images/logo.svg"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
  [[menu.header]]
    identifier = "about"
    name = "About Us"
    url = "/about"
    weight = 2
  [[menu.header]]
    identifier = "activities"
    name = "Activities"
    url = "/activities"
    weight = 3
  [[menu.header]]
    identifier = "activities"
    name = "Statement"
    url = "/mapathon-keralam-osm-community-statement/"
    weight = 4
[[menu.header]]
    identifier = "community"
    name = "Community"
    url = "/building-osm-kerala-community/"
    weight = 5
